image: python:3.7-stretch

before_script:
      - echo "deb http://ftp.de.debian.org/debian testing main" >> /etc/apt/sources.list
      - apt-get update -qq
      - apt-get install -y -qq python3.7-dev
      - apt-get install -y -qq python3-pip
      - apt-get install -y -qq openmpi-bin
      - apt-get install -y -qq libopenmpi-dev
      - apt-get install -y -qq default-jdk
      - apt-get install -y -qq graphviz
      - apt-get install -y -qq ant
      - apt-get install -y -qq r-base
      - apt-get install -y -qq sqlite3
      - apt-get install -y -qq libssl-dev
      - apt-get install -y -qq libffi-dev
      - pip3 install -U pip tox

stages:
    - syntax
    - tests
    - integration
    - integration-long
    - clusters
    - pypi

syntax:
    stage: syntax
    allow_failure: false
    script:
        - tox -r -vv -e syntax

tests:
    stage: tests
    allow_failure: false
    variables:
        OMPI_MCA_rmaps_base_oversubscribe: "yes"
    script:
        - tox -r -vv -e tests

integration:
    stage: integration
    allow_failure: false
    variables:
        OMPI_MCA_rmaps_base_oversubscribe: "yes"
    script:
        - tox -r -vv -e integration

integration-long:
    stage: integration-long
    allow_failure: false
    only:
        - /^test.*$/
        - /^release$/
        - /^hotfixes$/
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
    variables:
        OMPI_MCA_rmaps_base_oversubscribe: "yes"
    script:
        - tox -r -vv -e integration-long

clusters:
    stage: clusters
    allow_failure: false
    only:
        - /^test.*$/
        - /^release$/
        - /^hotfixes$/
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
    variables:
        GIT_REPO_CI_BRANCH: $CI_COMMIT_REF_NAME
        SSH_PRV_KEY: $EULER_TESTS_SSH_PRV_KEY
        EULER_USER: $EULER_TESTS_USER
    script:
        - tests_euler/trigger_tests.sh

pypi:
    stage: pypi
    allow_failure: false
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
    variables:
        PYPI_USER: $PYPI_USER
        PYPI_PASSWD: $PYPI_PASSWD
    script:
        - pip3 install -U -r requirements_rtd.txt
        - python3 setup.py sdist bdist_wheel
        - twine upload --username $PYPI_USER --password $PYPI_PASSWD dist/*
